name: Deploy to Azure

on:
  push:
    branches:
      - main  # Replace with your branch name if it's not 'main'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v2

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.x'  # Replace with the desired .NET Core version

    - name: Change working directory to /src/
      working-directory: ./src/
      run: echo "Changed working directory to /src/"

    - name: Restore dependencies
      run: dotnet restore

    - name: Build the project
      run: dotnet publish Develorem.Discord.ChatGptBot.csproj -c Release -o ./Develorem.Discord.ChatGptBot/bin/Release/netcoreapp3.1/publish

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}